export const BrowseData = {
  accountInformation: {
    reconcilationStatus: "Area Approved",
    account: "282004",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "00001",
    product: "*",
    CW: "",
    zeroBalanceAccountMonthly: "No",
    zeroBalanceAccountEOY: "No",
    assignedReconciler: "Lisa D Block(A2KQ)",
    assignedApprover: "Nicky Burns(HBCY)",
    assignedAreaApprover: "Katy Lampe(I4EG)",
  },
  balanceInformation: {
    ledgerBalance: "$273,659.93",
    controlBalance: "$273,659.93",
    outstandingListing: "$0.00",
    difference: "$0.00",
  },
  explanation: "",
  actionPlan: "",
  estimatedDateOfResolution: "",
  statusHistory: {
    openedDate: "03/13/2020 02:16:33 AM",
    reconciledDate: "03/13/2020 02:16:33 AM",
    reconciledBy: "by System Reconciled",
    approvedDate: "03/13/2020 02:16:33 AM",
    approvedBy: "by System Approved",
    areaApprovedDate: "03/17/2020 09:35:37 AM",
    areaApprovedBy: "Katy Lampe(I4EG)",
  },
  editHistory: {
    openedDate: "03/13/2020 02:16:33 AM",
    reconciledDate: "03/13/2020 02:16:33 AM",
    reconciledBy: "by System Reconciled",
    approvedDate: "03/13/2020 02:16:33 AM",
    approvedBy: "by System Approved",
    areaApprovedDate: "03/17/2020 09:35:37 AM",
    areaApprovedBy: "Katy Lampe(I4EG)",
  },
};

export const area = [
  "",
  "00 BENEFITS UNIT MY",
  "00 BENEFITS UNIT XH",
  "00 FRA ASSET MANAGEMENT-FME/IT",
  "00 FRA ASSET MGMT-PROPERTIES",
  "00 FRA LA&amp;C",
  "00 FRA LEDGER",
  "00 FRA RM REINS",
  "00 FRR IPS",
  "00 FSS 1099 EARNINGS REPORTING",
];

export const year = ["", "2021", "2020", "2019", "2018", "2017", "2016"];

export const month = [
  "",
  "Jan-01",
  "Feb-02",
  "Mar-03",
  "Apr-04",
  "May-05",
  "Jun-06",
  "Jul-07",
  "Aug-08",
  "Sep-09",
  "Oct-10",
  "Nov-11",
  "Dec-12",
];

export const status = ["", "open", "Reconciled", "Approved", "Area Approved"];

export const responseContent = [
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011001",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011002",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011003",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011004",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011005",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011006",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011007",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011008",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "3011009",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100110",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100111",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100112",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100113",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100114",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100115",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100116",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100117",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100118",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100119",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100120",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100121",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100122",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100123",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100124",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100125",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100126",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100127",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
  {
    date: "2021-01",
    area: "00 BENEFITS UNIT MY",
    businessUnit: "305",
    account: "301100128",
    product: "*",
    assignedReconciler: "Lisa D Block",
    assignedApprover: "Nicky Burns",
    assignedAreaApprover: "Lisa Estamas",
    ledgerBalance: "67",
    controlBalance: "4.3",
    outstandingListing: "67",
    difference: "4.3",
    status: "open",
  },
];
